export const formatsDateTime = {
  yearMonthDay: 'YYYY-MM-DD',
  monthDay: 'MMM D',
  dateTimeMachine: 'YYYY-MM-DDTHH:mm',
  dateTimeHumanize: 'DD/MM/YY HH:mm',
  time: 'HH:mm',
};

export const offerNames = {
  upgradeComfort: 'Upgrade to comfort class',
  chooseComfort: 'Choose comfort class',
  chooseBusiness: 'Choose business class',
  upgradeBusiness: 'Upgrade to a business class',
  airBusiness: 'Upgrade to business class',
  radio: 'Choose the radio station',
  temperature: 'Choose temperature',
  hurry: `Drive quickly, I'm in a hurry`,
  slowly: 'Drive slowly',
  info: 'Infotainment system',
  orderMeal: 'Order meal',
  chooseMeal: 'Choose meal',
  restaurantMeal: 'Order a meal from the restaurant',
  seats: 'Choose seats',
  taxi: 'Book a taxi at the arrival point',
  orderBreakfast: 'Order a breakfast',
  addBreakfast: 'Add breakfast',
  wakeup: 'Wake up at a certain time',
  luggage: 'Add luggage',
  lounge: 'Business lounge',
  checkin: 'Choose the time of check-in',
  checkout: 'Choose the time of check-out',
  laundry: 'Laundry',
  music: 'Choose live music',
  vip: 'Choose VIP area',
};
